### ISSUE TITLE
add system ports to InternetSender

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/terrame#200]
Add system ports to Observer as well as InternetSender. Today it is only:

```lua
        if pt == 80 or pt == 8080 then
            customError("Observers UDP should not use system ports.", 4)
```

**Comment by avancinirodrigo** [comment]
use switch

**Comment by avancinirodrigo** [comment]
All registered porting can be found in: 
http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=2
